version = 1

[[annotations]]
path = [
    "Tests/SSUtilLibTests/Resources/inputs/**",
    "Tests/SSUtilLibTests/__Snapshots__/**"
]
SPDX-FileCopyrightText = "2025 Lukas Kollmer"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "Tests/SSUtilLibTests/Resources/bezels**"
]
SPDX-FileCopyrightText = "NOASSERTION"
SPDX-License-Identifier = "NOASSERTION"