#
# This source file is part of the Stanford Biodesign Digital Health Group open-source organization
#
# SPDX-FileCopyrightText: 2025 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  releasetag:
    name: Tag Release
    uses: StanfordBDHG/.github/.github/workflows/action-release-tag.yml@v2
    permissions:
      contents: write
  build-and-upload:
    name: Build and Upload Binaries
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6"
      - name: Build binary
        run: swift build -c release --product ssutil
      - name: Create archive
        run: |
          cd .build/release
          tar -czf ssutil-macos.tar.gz ssutil
      - name: Upload binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} .build/release/ssutil-macos.tar.gz